### ISSUE TITLE
Launching Web UI on New Project Times out at "/app/signup"

### ISSUE THREAD

**Issue by qcomer** [Nodewood/issues#5]
Any thoughts or ideas?

nginx_1     | [REDACTED] - - [28/Dec/2021:23:38:55 +0000] "GET /app/signup HTTP/1.1" 499 0 "https://[REDACTED]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62" "-"

nginx_1     | 2021/12/28 23:39:57 [error] 30#30: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: [REDACTED], server: _, request: "GET /app/signup HTTP/1.1", upstream: "http://[REDACTED]:9000/app/signup", host: "[REDACTED]", referrer: "https://[REDACTED]/"
nginx_1     | [REDACTED] - - [28/Dec/2021:23:39:57 +0000] "GET /app/signup HTTP/1.1" 504 569 "https://[REDACTED]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62" "-"
nginx_1     | [REDACTED] - - [28/Dec/2021:23:40:42 +0000] "GET / HTTP/1.1" 200 858 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62" "-"

Ive read through the NGINX logs and its not very clear. Appeears the :9000 server isnt responding or is timing out.

This is when a project is initially created, migrated and run

**Comment by DanHulton** [comment]
It looks like the UI container isn't running for some reason.  If you scroll up to the logs that start with `ui_1 |`, there should be more information about why.

Alternatively, stopping and restarting the containers (Ctrl-C to stop, `nodewood dev` again to restart) can help if you're experiencing an intermittent Docker issue (such as running out of swap or disk space).

**Comment by qcomer** [comment]
ui_1        | yarn run v1.22.15
ui_1        | $ cd app && vue-cli-service serve

followed later by
ui_1        |  INFO  Starting development server...

**Comment by DanHulton** [comment]
It looks like your UI is taking a long time to start up.  In development mode, Nodewood uses nginx to proxy requests for the UI to a webpack development server running at port 9000 in the UI container.  If that development server isn't running by the time nginx reaches its proxy timeout period, it fails.

There are a variety of things we can do to address this.

1) Restart the nginx container after the UI server is running.

Eventually you should see similar to the following, indicating your UI development server is running:
```
ui_1        |  DONE  Compiled successfully in 13225ms1:03:10 AM
ui_1        |
ui_1        | Webpack Bundle Analyzer is started at http://0.0.0.0:8888
ui_1        | Use Ctrl+C to close it
ui_1        |
ui_1        |   App running at:
ui_1        |   - Local:   http://localhost:9000/app/
ui_1        |   - Network: http://nodewood.test/
ui_1        |
ui_1        |   Note that the development build is not optimized.
ui_1        |   To create a production build, run npm run build.
```
From a different terminal window, run `docker ps` and you should get a list of running containers.  Copy the `CONTAINIER ID` entry for the "something_nginx" `IMAGE` row.  Then run `docker container restart CONTAINERID`, where `CONTAINERID` is what you just copied.

Nginx should restart and connect to your docker container.

2) Speed up your UI development server.

If you are running on MacOS, the default Docker setup can be _incredibly_ slow due to the very slow file synchronization strategy it uses by default.  You can get around this by using Mutagen, a much faster file sync tool.  [I have an article about why and how to do just that](https://nodewood.com/blog/how-to-speed-up-docker-on-macos/).

You actually probably want to do this anyway, if you're on MacOS, even if you end up solving this problem in another way.  You're going to have a much better time developing Nodewood or really anything using Docker if you use Mutagen to do the file synchronization.

3) It should really reconnect by itself automatically.

As of now, I've created a ticket for just this, and will hopefully add it in as part of the 0.20.0 release, which should be coming shortly.  Apologies for the inconvenience!

**Comment by qcomer** [comment]
I turned on progress for the loading of the UI server and that’s in fact what it was. Stalling at 54%. 

I added some more resources to it and away it went! 

Running it on a CentOS server in Digital Ocean for now.

**Comment by DanHulton** [comment]
Ah, absolutely that would do it.  I should add something to the documentation and mention that it needs at least 2GB of RAM to compile correctly.  Normally not an issue locally, since Docker defaults to something between 2GB and 4GB of RAM on install, but a 1GB VM would definitely not be big enough to compile the UI.

Marking as resolved!
