### ISSUE TITLE
Prisma with Nodewood

### ISSUE THREAD

**Issue by tucson129** [Nodewood/issues#6]
I'd like to be able to have Nodewood share an existing MS SQL Server database with other applications using Prisma.

To do this I created a new Nodewood project and setup a copy of my SQL Server database in a docker container connected to the project's docker network.

After installing Prisma in my Nodewood project, I can return records from the SQL database when I call it from the following test file.

app/prismaTest.js

    const { PrismaClient } = require('@prisma/client');

    const prisma = new PrismaClient();

    async function main() {
      const allEmps = await prisma.nwEmployee.findMany();
      console.log(allEmps);
    };

    main()
      .catch((e) => {
        throw e;
      })
      .finally(async () => {
        await prisma.$disconnect();
      });

When I then copy and paste the exact same require line

    const { PrismaClient } = require('@prisma/client');

into the same Nodewood project's app/api/AppBuilder.js, it throws this error

    api_1       | [nodemon] restarting due to changes...
    api_1       | [nodemon] starting `node ./api.js`
    api_1       | Error: Cannot find module 'encoding'
    api_1       | Require stack:
    api_1       | - /nodewood/node_modules/@prisma/client/runtime/index.js
    api_1       |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    api_1       |     at Function.Module._resolveFilename (/nodewood/node_modules/module-alias/index.js:49:29)
    api_1       |     at Module.fallbackRequire [as require] (/nodewood/wood/api/Require.js:37:35)
    api_1       |     at require (node:internal/modules/cjs/helpers:102:18)
    api_1       |     at /nodewood/node_modules/@prisma/client/runtime/index.js:15392:19
    api_1       |     at /nodewood/node_modules/@prisma/client/runtime/index.js:3298:9
    api_1       |     at /nodewood/node_modules/@prisma/client/runtime/index.js:24457:43
    api_1       |     at /nodewood/node_modules/@prisma/client/runtime/index.js:3298:9
    api_1       |     at /nodewood/node_modules/@prisma/client/runtime/index.js:24917:27
    api_1       |     at /nodewood/node_modules/@prisma/client/runtime/index.js:3298:9 {
    api_1       |   code: 'MODULE_NOT_FOUND',
    api_1       |   requireStack: [ '/nodewood/node_modules/@prisma/client/runtime/index.js' ]
    api_1       | }
    api_1       | [nodemon] app crashed - waiting for file changes before starting...

I further added the line

    require('../wood/api/Require');

to the app/prismaTest.js that was working earlier, now it is throwing the same "Cannot find module 'encoding'" error.

It seems like the problem is in wood/api/Require.js, but I don't know enough to debug it.

Would you be able to help me with this?

**Comment by DanHulton** [comment]
Nodewood makes extensive use of [MassiveJS](https://gitlab.com/dmfay/massive-js), a data mapper for Postgres, so use of another database toolkit and indeed an entirely different database is not something I can provide extensive support with.  Honestly, it may not work at all without serious rewrites of a lot of core Nodewood code.

That said, I think I understand why you're getting this particular error and it has to do with how Nodewood modifies Node.js's require function.  In order to rewrite things like `require('#features/users/lib/models/UserModel')` to target either the `app` folder if the model exists there, or fall back to the `wood` folder, we save the original `require()` function and replace it with our own that does some folder checking for these files.  If it cannot find it in _either_ of those locations, it calls the original `require` function, exiting with an error message if the module cannot be loaded.

Prisma uses a version of [node-fetch](https://github.com/node-fetch/node-fetch) that _optionally_ uses the "encoding" library.  The way they optionally make use of this library is as follows:

```javascript
  try {
    convert = require("encoding").convert;
  } catch (e) {
  }

 // ...

  if (typeof convert !== "function") {
    throw new Error("The package `encoding` must be installed to use the textConverted() function");
  }
```

In Nodewood, what happens is that the require function fails, and then the program is exited, instead of continuing gracefully.

Longer-term, I will investigate whether I can safely drop the `process.exit` from Nodewood's modified `require()` function, but in the short term, you can solve this immediate problem by running `yarn install encoding` in your Nodewood project.  This will ensure that this require passes successfully and the execution is not halted here.

I wish you good luck in getting this to work the way you intend, though again, I won't be able to offer any support in terms of broad rewrites of database functionality.

**Comment by tucson129** [comment]
Thank you for your advice.

I installed the encoding module and got it working. After that, I came across other problems, and as you said, it may not be possible to easily work with other databases.

I'll keep going a little more and let you know what happens.
